scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-ip:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['linux-host-ip1:9100','linux-host-ip2:9100','linux-host-ip3:9100']
  - job_name: 'windows_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['windows-host-ip1:9182','windows-host-ip2:9182']
