---
- name: build and run elk
  hosts: docker-host
  become: yes
  remote_user: ec2-user
  become_user: root

  tasks:
    - include_role:
        name: prepare_docker_host

    - name: copy files to remote host
      copy:
        src: {{ item.src }}
        dest: {{ item.dest }}
      with_items:
      - { src: ../grafana/, dest: /opt/prometheus_grafana/grafana/ }
      - { src: ../prometheus/, dest: /opt/prometheus_grafana/prometheus/ }
      - { src: ../docker-compose.yaml, dest: /opt/prometheus_grafana/ }
    
    # use files parameter to use multiple docker-compose.yml files

    - name: deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /opt/prometheus_grafana/
        files:
        - docker-compose.yaml